# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(max_length=40)),
                ('uf', models.CharField(choices=[('rn', 'Rio Grande do Norte'), ('pe', 'Pernabuco'), ('pb', 'Paraiba')], max_length=2)),
                ('telefone', models.CharField(max_length=13)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
