# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='data_nascimento',
            new_name='data_nasc',
        ),
    ]
