# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_auto_20170303_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('modalidade', models.CharField(choices=[('boxe', 'Boxe'), ('capoeira', 'Capoeira'), ('judo', 'Jud\xf4'), ('taekwond', 'Taekwond'), ('mma', 'MMA'), ('jiujitsu', 'Jiu Jitsu'), ('karate', 'Karat\xea'), ('zumba', 'Zumba'), ('outra', 'Outra')], max_length=13)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('dia_vencimento', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
