# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_auto_20170303_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='turma',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
