# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_auto_20170303_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='status',
            new_name='Pago',
        ),
    ]
