# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_auto_20170303_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='anotacoes_aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('anotacao', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.aluno')),
            ],
        ),
    ]
