# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0010_auto_20170303_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro(R$)'), ('Cart\xe3o', 'Cart\xe3o'), ('Tranferencia', 'Tranfer\xeancia')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('turma_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.turma_aluno')),
            ],
        ),
    ]
