# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0011_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='pago',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
