# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0013_auto_20170306_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
