# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0014_aluno_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='turma_aluno',
            name='dia_vencimento',
            field=models.CharField(default='02', max_length=2),
        ),
    ]
