# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0015_auto_20170308_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='mes',
            field=models.CharField(choices=[('9', 'SETEMBRRO'), ('6', 'JUNHO'), ('5', 'MAIO'), ('12', 'DEZEMBRO'), ('10', 'OUTUBRO'), ('2', 'FEVEREIRO'), ('8', 'AGOSTO'), ('7', 'JULHO'), ('3', 'MAR\xc7O'), ('4', 'ABRIL'), ('11', 'NOVEMBRO'), ('1', 'JANEIRO')], default=3, max_length=2),
            preserve_default=False,
        ),
    ]
