# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0016_recibo_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
